import type React from "react";

export const lcarsPageStyles: Record<string, React.CSSProperties> = {
  pageTitle: {
    fontFamily: "'Orbitron', sans-serif",
    fontSize: 22,
    fontWeight: 700,
    marginBottom: 10,
    color: "var(--lcars-orange)",
    letterSpacing: "4px",
    textTransform: "uppercase" as const,
  },
  pageTitleBar: {
    height: 6,
    background:
      "linear-gradient(90deg, var(--lcars-orange) 0%, rgba(255, 153, 0, 0.5) 38%, rgba(153, 153, 204, 0.14) 72%, transparent 100%)",
    marginBottom: 24,
    borderRadius: "0 18px 18px 0",
    boxShadow: "0 0 18px rgba(255, 153, 0, 0.08)",
  },
  card: {
    background: "var(--bg-console)",
    border: "1px solid rgba(153, 153, 204, 0.16)",
    borderLeft: "8px solid var(--lcars-peach)",
    borderRadius: "0 22px 0 0",
    padding: 24,
    marginBottom: 20,
    boxShadow:
      "inset 0 1px 0 rgba(255,255,255,0.03), 0 18px 30px rgba(0, 0, 0, 0.24)",
  },
  subtleCard: {
    background: "var(--bg-console-soft)",
    border: "1px solid rgba(153, 153, 204, 0.14)",
    borderLeft: "6px solid var(--lcars-peach)",
    borderRadius: "0 18px 18px 0",
    padding: 16,
    boxShadow:
      "inset 0 1px 0 rgba(255,255,255,0.03), 0 12px 24px rgba(0, 0, 0, 0.18)",
  },
  sectionTitle: {
    fontFamily: "'Orbitron', sans-serif",
    fontSize: 12,
    fontWeight: 600,
    color: "var(--lcars-orange)",
    marginBottom: 8,
    letterSpacing: "2px",
    textTransform: "uppercase" as const,
  },
  sectionDivider: {
    height: 2,
    background:
      "linear-gradient(90deg, rgba(255, 153, 0, 0.35), rgba(153, 153, 204, 0.1) 70%, transparent)",
    marginBottom: 16,
  },
  table: {
    width: "100%",
    borderCollapse: "separate" as const,
    borderSpacing: 0,
    fontSize: 13,
  },
  th: {
    textAlign: "left" as const,
    color: "var(--lcars-lavender)",
    fontFamily: "'Orbitron', sans-serif",
    fontWeight: 500,
    padding: "10px 12px",
    borderBottom: "1px solid rgba(255, 153, 0, 0.18)",
    fontSize: 10,
    textTransform: "uppercase" as const,
    letterSpacing: "1.5px",
    background: "rgba(255, 153, 0, 0.08)",
  },
  td: {
    padding: "12px 12px",
    color: "var(--lcars-tan)",
    borderBottom: "1px solid rgba(153, 153, 204, 0.08)",
    background: "rgba(153, 153, 204, 0.015)",
  },
  tdMono: {
    padding: "12px 12px",
    color: "var(--lcars-lavender)",
    borderBottom: "1px solid rgba(153, 153, 204, 0.08)",
    background: "rgba(153, 153, 204, 0.015)",
    fontFamily: "'JetBrains Mono', monospace",
  },
  emptyText: {
    fontFamily: "'Orbitron', sans-serif",
    fontSize: 11,
    color: "var(--text-quaternary)",
    letterSpacing: "2px",
    textTransform: "uppercase" as const,
  },
  input: {
    width: "100%",
    background: "rgba(10, 10, 20, 0.84)",
    border: "1px solid rgba(153, 153, 204, 0.18)",
    borderLeft: "4px solid rgba(255, 153, 0, 0.3)",
    color: "var(--lcars-tan)",
    padding: "10px 12px",
    fontSize: 13,
    fontFamily: "'JetBrains Mono', monospace",
    outline: "none",
    borderRadius: "0 12px 12px 0",
  },
  primaryButton: {
    background: "linear-gradient(90deg, var(--lcars-orange), #ffb347)",
    color: "#111",
    border: "none",
    borderRadius: "0 14px 14px 0",
    padding: "10px 16px",
    fontFamily: "'Orbitron', sans-serif",
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "1px",
    cursor: "pointer",
    boxShadow: "inset 0 1px 0 rgba(255,255,255,0.16), var(--glow-orange)",
  },
  ghostButton: {
    background: "rgba(10, 10, 20, 0.68)",
    color: "var(--lcars-lavender)",
    border: "1px solid rgba(153, 153, 204, 0.25)",
    borderRadius: "0 14px 14px 0",
    padding: "10px 16px",
    fontFamily: "'Orbitron', sans-serif",
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "1px",
    cursor: "pointer",
  },
  buttonRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap" as const,
    marginBottom: 12,
  },
  helperText: {
    fontSize: 11,
    color: "var(--lcars-lavender)",
    lineHeight: 1.6,
    letterSpacing: "0.45px",
  },
  metricLabel: {
    fontFamily: "'Orbitron', sans-serif",
    fontSize: 10,
    fontWeight: 500,
    color: "var(--lcars-lavender)",
    marginBottom: 8,
    letterSpacing: "1.5px",
    textTransform: "uppercase" as const,
  },
  metricValue: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: 28,
    fontWeight: 600,
    color: "var(--lcars-orange)",
    letterSpacing: "-0.5px",
  },
  toolbar: {
    display: "flex",
    gap: 12,
    alignItems: "center",
    flexWrap: "wrap" as const,
    marginBottom: 20,
  },
};
