import type { CortexCommand, CortexGraph } from "./types";

export const CORTEX_COMMANDS: CortexCommand[] = [
  {
    id: "trace-signal",
    label: "Trace Signal",
    description: "Reveal recent events and agent traces connected to this node.",
    allowedNodeKinds: ["mission", "client", "project", "issue", "agent", "human", "routine"],
  },
  {
    id: "summon-agent",
    label: "Summon Agent",
    description: "Bring the most relevant agent into this operational branch.",
    allowedNodeKinds: ["mission", "client", "project", "issue", "approval"],
  },
  {
    id: "stabilize-branch",
    label: "Stabilize Branch",
    description: "Request a stabilizing plan for a risky client or work branch.",
    allowedNodeKinds: ["client", "project", "issue"],
  },
  {
    id: "approve-synapse",
    label: "Approve Synapse",
    description: "Approve a waiting decision gate.",
    allowedNodeKinds: ["approval", "issue", "project"],
  },
  {
    id: "escalate-human",
    label: "Escalate Human",
    description: "Route the node to a human anchor for judgment.",
    allowedNodeKinds: ["issue", "approval", "project", "agent"],
  },
  {
    id: "generate-brief",
    label: "Generate Brief",
    description: "Synthesize a tactical brief from node context.",
    allowedNodeKinds: ["mission", "client", "project", "issue", "agent", "memory"],
  },
  {
    id: "split-pathway",
    label: "Split Pathway",
    description: "Fork a workstream into a separate execution branch.",
    allowedNodeKinds: ["project", "issue"],
  },
  {
    id: "extract-memory",
    label: "Extract Memory",
    description: "Pull relevant knowledge into the active branch.",
    allowedNodeKinds: ["memory", "mission", "project"],
  },
  {
    id: "route-work",
    label: "Route Work",
    description: "Assign work to the best available human or agent node.",
    allowedNodeKinds: ["mission", "project", "issue", "approval"],
  },
  {
    id: "quarantine-risk",
    label: "Quarantine Risk",
    description: "Isolate a risky branch until it can be stabilized.",
    allowedNodeKinds: ["issue", "project", "client"],
  },
];

export const sampleCortexGraph: CortexGraph = {
  id: "sample-mission-cortex",
  label: "Mission Cortex Sample Graph",
  generatedAt: "2026-06-12T00:00:00.000Z",
  nodes: [
    {
      id: "mission:current",
      kind: "mission",
      label: "Mission Nucleus",
      state: "active",
      position: { x: 500, y: 330 },
      source: "teamforge",
      summary: "Founder attention surface for active delivery, agents, and risk.",
      commands: ["trace-signal", "summon-agent", "generate-brief"],
      lensAffinity: ["mission", "risk", "signals"],
    },
    {
      id: "client:thoughtseed",
      kind: "client",
      label: "Thoughtseed",
      state: "healthy",
      position: { x: 250, y: 210 },
      source: "teamforge",
      metrics: [{ label: "Active branches", value: "4", state: "active" }],
      commands: ["trace-signal", "stabilize-branch", "generate-brief"],
      lensAffinity: ["clients", "mission"],
    },
    {
      id: "project:paperclip-control",
      kind: "project",
      label: "Paperclip Control Plane",
      state: "active",
      position: { x: 365, y: 130 },
      source: "huly",
      metrics: [{ label: "Flow", value: "72%", state: "active" }],
      commands: ["trace-signal", "summon-agent", "split-pathway", "generate-brief"],
      lensAffinity: ["work", "agents"],
    },
    {
      id: "issue:review-gate",
      kind: "issue",
      label: "Review Gate",
      state: "pending",
      position: { x: 650, y: 170 },
      source: "github",
      metrics: [{ label: "Pending", value: "3", state: "pending" }],
      commands: ["trace-signal", "approve-synapse", "escalate-human"],
      lensAffinity: ["risk", "work", "mission"],
    },
    {
      id: "issue:blocked-sync",
      kind: "issue",
      label: "Blocked Sync",
      state: "blocked",
      position: { x: 745, y: 425 },
      source: "github",
      metrics: [{ label: "Inflammation", value: "High", state: "blocked" }],
      commands: ["trace-signal", "quarantine-risk", "escalate-human"],
      lensAffinity: ["risk", "signals"],
    },
    {
      id: "agent:hermes",
      kind: "agent",
      label: "Hermes-Sync",
      state: "healthy",
      position: { x: 830, y: 280 },
      source: "paperclip",
      metrics: [{ label: "Tasks", value: "12", state: "healthy" }],
      commands: ["trace-signal", "generate-brief"],
      lensAffinity: ["agents", "signals"],
    },
    {
      id: "human:founder",
      kind: "human",
      label: "Founder Anchor",
      state: "active",
      position: { x: 500, y: 560 },
      source: "manual",
      commands: ["trace-signal", "generate-brief"],
      lensAffinity: ["mission", "risk"],
    },
    {
      id: "memory:operating-context",
      kind: "memory",
      label: "Operating Context",
      state: "dormant",
      position: { x: 185, y: 500 },
      source: "teamforge",
      commands: ["extract-memory", "generate-brief"],
      lensAffinity: ["memory", "mission"],
    },
  ],
  paths: [
    { id: "path:mission-client", kind: "ownership", from: "mission:current", to: "client:thoughtseed", state: "healthy", source: "teamforge", signalCount: 2 },
    { id: "path:client-project", kind: "execution", from: "client:thoughtseed", to: "project:paperclip-control", state: "active", source: "huly", signalCount: 8 },
    { id: "path:project-review", kind: "risk", from: "project:paperclip-control", to: "issue:review-gate", state: "pending", source: "github", signalCount: 3 },
    { id: "path:project-agent", kind: "handoff", from: "project:paperclip-control", to: "agent:hermes", state: "healthy", source: "paperclip", signalCount: 12 },
    { id: "path:agent-blocked", kind: "risk", from: "agent:hermes", to: "issue:blocked-sync", state: "blocked", source: "paperclip", signalCount: 1 },
    { id: "path:mission-human", kind: "handoff", from: "mission:current", to: "human:founder", state: "active", source: "manual", signalCount: 4 },
    { id: "path:mission-memory", kind: "memory", from: "mission:current", to: "memory:operating-context", state: "dormant", source: "teamforge" },
  ],
  signals: [
    { id: "signal:hermes-flow", pathId: "path:project-agent", state: "healthy", source: "paperclip", label: "Hermes synced project graph" },
    { id: "signal:review-pending", pathId: "path:project-review", state: "pending", source: "github", label: "Founder approval waiting" },
    { id: "signal:blocked-sync", pathId: "path:agent-blocked", state: "blocked", source: "paperclip", label: "Sync path constricted" },
  ],
};
